# -*- coding: utf-8 -*-
"""question2 and 3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qR38yqROvls_yG_4bPM9XGPgDXVb4D_Q
"""

import numpy as np
import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap
import heapq
import time
import random

# --- Configuration ---
# You can change these values directly here before running the cell
GRID_SIZE = 70
# Density Options: 0.15 (Low), 0.30 (Medium), 0.45 (High)
OBSTACLE_DENSITY = 0.45

def create_grid(size, density_prob):
    """Generates a 2D grid with random obstacles."""
    grid = []
    for _ in range(size):
        row = [1 if random.random() < density_prob else 0 for _ in range(size)]
        grid.append(row)
    return grid

def heuristic(a, b):
    """Manhattan distance heuristic."""
    return abs(a[0] - b[0]) + abs(a[1] - b[1])

def get_neighbors(node, grid):
    """Returns valid, non-obstacle neighbor coordinates."""
    directions = [(0, 1), (1, 0), (0, -1), (-1, 0)]
    neighbors = []

    for dx, dy in directions:
        nx, ny = node[0] + dx, node[1] + dy
        if 0 <= nx < GRID_SIZE and 0 <= ny < GRID_SIZE and grid[nx][ny] == 0:
            neighbors.append((nx, ny))
    return neighbors

def astar_search(grid, start, goal):
    """Executes A* Search and returns path and nodes explored."""
    open_set = []
    heapq.heappush(open_set, (0, start))
    came_from = {}
    g_score = {start: 0}
    nodes_explored = 0

    while open_set:
        _, current = heapq.heappop(open_set)
        nodes_explored += 1

        if current == goal:
            path = []
            while current in came_from:
                path.append(current)
                current = came_from[current]
            path.append(start)
            path.reverse()
            return path, nodes_explored

        for neighbor in get_neighbors(current, grid):
            tentative_g_score = g_score[current] + 1
            if neighbor not in g_score or tentative_g_score < g_score[neighbor]:
                came_from[neighbor] = current
                g_score[neighbor] = tentative_g_score
                f_score = tentative_g_score + heuristic(neighbor, goal)
                heapq.heappush(open_set, (f_score, neighbor))

    return None, nodes_explored

def visualize_grid(grid, start, goal, path):
    """Uses Matplotlib to draw the battlefield and the UGV's path."""
    # Create a visual matrix: 0=Empty, 1=Obstacle, 2=Start, 3=Goal, 4=Path
    vis_matrix = np.array(grid)

    if path:
        for (x, y) in path:
            vis_matrix[x][y] = 4

    vis_matrix[start[0]][start[1]] = 2
    vis_matrix[goal[0]][goal[1]] = 3

    # Define colors: White (Empty), Black (Obstacle), Green (Start), Red (Goal), Blue (Path)
    cmap = ListedColormap(['#f0f0f0', '#2d2d2d', '#00ff00', '#ff0000', '#0088ff'])

    plt.figure(figsize=(10, 10))
    plt.imshow(vis_matrix, cmap=cmap)
    plt.title(f"UGV Battlefield Navigation ({GRID_SIZE}x{GRID_SIZE})", fontsize=16)

    # Create a custom legend
    from matplotlib.patches import Patch
    legend_elements = [
        Patch(facecolor='#f0f0f0', edgecolor='gray', label='Open Terrain'),
        Patch(facecolor='#2d2d2d', label='Static Obstacle'),
        Patch(facecolor='#00ff00', label='Start Node'),
        Patch(facecolor='#ff0000', label='Goal Node'),
        Patch(facecolor='#0088ff', label='Optimal Path')
    ]
    plt.legend(handles=legend_elements, loc='upper right', bbox_to_anchor=(1.3, 1))

    plt.axis('off')
    plt.show()

# --- Execution ---
print(f"--- UGV Battlefield Pathfinding ({GRID_SIZE}x{GRID_SIZE} km) ---")
print(f"Generating map with {OBSTACLE_DENSITY*100}% obstacle density...\n")

battlefield = create_grid(GRID_SIZE, OBSTACLE_DENSITY)

start_node = (0, 0)
goal_node = (GRID_SIZE - 1, GRID_SIZE - 1)

# Ensure start and goal are open terrain
battlefield[start_node[0]][start_node[1]] = 0
battlefield[goal_node[0]][goal_node[1]] = 0

start_time = time.perf_counter()
optimal_path, total_explored = astar_search(battlefield, start_node, goal_node)
end_time = time.perf_counter()

execution_time_ms = (end_time - start_time) * 1000

# Output MoE
print("="*40)
print(" MEASURES OF EFFECTIVENESS (MoE)")
print("="*40)
print(f"Execution Time:    {execution_time_ms:.4f} ms")
print(f"Nodes Explored:    {total_explored} nodes")

if optimal_path:
    print(f"Path Found:        YES")
    print(f"Total Distance:    {len(optimal_path) - 1} km")
else:
    print(f"Path Found:        NO (Target Blocked)")
print("="*40 + "\n")

# Render Map
visualize_grid(battlefield, start_node, goal_node, optimal_path)

import numpy as np
import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap
import heapq
import time
import random

# --- Configuration ---
GRID_SIZE = 70
OBSTACLE_DENSITY = 0.30
SENSOR_RANGE = 3  # How far the UGV can "see" around itself in grid units

def create_true_environment(size, density_prob):
    """Generates the 'real' world with obstacles that the UGV doesn't know about yet."""
    return [[1 if random.random() < density_prob else 0 for _ in range(size)] for _ in range(size)]

def heuristic(a, b):
    return abs(a[0] - b[0]) + abs(a[1] - b[1])

def get_neighbors(node, grid):
    directions = [(0, 1), (1, 0), (0, -1), (-1, 0)]
    neighbors = []
    for dx, dy in directions:
        nx, ny = node[0] + dx, node[1] + dy
        # Only return neighbors that are within bounds and NOT known obstacles
        if 0 <= nx < GRID_SIZE and 0 <= ny < GRID_SIZE and grid[nx][ny] == 0:
            neighbors.append((nx, ny))
    return neighbors

def astar_replan(grid, start, goal):
    """Calculates a path from the current position using the UGV's currently known map."""
    open_set = []
    heapq.heappush(open_set, (0, start))
    came_from = {}
    g_score = {start: 0}

    while open_set:
        _, current = heapq.heappop(open_set)

        if current == goal:
            path = []
            while current in came_from:
                path.append(current)
                current = came_from[current]
            path.reverse()
            return path # Returns the steps to take (excluding the start node itself)

        for neighbor in get_neighbors(current, grid):
            tentative_g_score = g_score[current] + 1
            if neighbor not in g_score or tentative_g_score < g_score[neighbor]:
                came_from[neighbor] = current
                g_score[neighbor] = tentative_g_score
                f_score = tentative_g_score + heuristic(neighbor, goal)
                heapq.heappush(open_set, (f_score, neighbor))

    return None # No path found

def dynamic_navigation(true_world, start, goal):
    """Simulates the UGV moving through the world, discovering obstacles, and replanning."""
    # The UGV starts completely blind (assumes the whole grid is 0 / empty)
    known_world = [[0 for _ in range(GRID_SIZE)] for _ in range(GRID_SIZE)]

    current_pos = start
    actual_path_taken = [start]
    planned_path = []
    replan_count = 0
    nodes_explored_total = 0

    while current_pos != goal:
        # 1. SENSOR PHASE: Update known_world with true_world data within SENSOR_RANGE
        for dx in range(-SENSOR_RANGE, SENSOR_RANGE + 1):
            for dy in range(-SENSOR_RANGE, SENSOR_RANGE + 1):
                nx, ny = current_pos[0] + dx, current_pos[1] + dy
                if 0 <= nx < GRID_SIZE and 0 <= ny < GRID_SIZE:
                    known_world[nx][ny] = true_world[nx][ny]

        # 2. EVALUATION PHASE: Check if the current plan is ruined by new obstacles
        needs_replanning = False
        if not planned_path:
            needs_replanning = True
        else:
            for step in planned_path:
                if known_world[step[0]][step[1]] == 1:
                    needs_replanning = True
                    break

        # 3. REPLANNING PHASE: Calculate a new route if necessary
        if needs_replanning:
            planned_path = astar_replan(known_world, current_pos, goal)
            replan_count += 1

            # If astar_replan returns None, the UGV is completely boxed in
            if not planned_path:
                return actual_path_taken, known_world, False, replan_count

        # 4. MOVEMENT PHASE: Take exactly one step along the planned path
        next_step = planned_path.pop(0)
        current_pos = next_step
        actual_path_taken.append(current_pos)

    return actual_path_taken, known_world, True, replan_count

def visualize_dynamic_run(true_grid, known_grid, start, goal, path):
    """Renders the final state of the dynamic run."""
    vis_matrix = np.zeros((GRID_SIZE, GRID_SIZE))

    # Map the visual states
    for x in range(GRID_SIZE):
        for y in range(GRID_SIZE):
            if true_grid[x][y] == 1:
                # If obstacle was discovered, mark it dark. If undiscovered, mark it light gray
                vis_matrix[x][y] = 1 if known_grid[x][y] == 1 else 5

    if path:
        for (x, y) in path:
            vis_matrix[x][y] = 4

    vis_matrix[start[0]][start[1]] = 2
    vis_matrix[goal[0]][goal[1]] = 3

    # Colors: 0=Empty(White), 1=Discovered Obstacle(Black), 2=Start(Green), 3=Goal(Red), 4=Path(Blue), 5=Undiscovered Obstacle(Light Gray)
    cmap = ListedColormap(['#ffffff', '#000000', '#00ff00', '#ff0000', '#0088ff', '#d3d3d3'])

    plt.figure(figsize=(10, 10))
    plt.imshow(vis_matrix, cmap=cmap)
    plt.title("Dynamic UGV Navigation (Continuous Replanning)", fontsize=16)

    from matplotlib.patches import Patch
    legend_elements = [
        Patch(facecolor='#ffffff', edgecolor='gray', label='Open Terrain'),
        Patch(facecolor='#d3d3d3', label='Undiscovered Obstacle'),
        Patch(facecolor='#000000', label='Discovered Obstacle'),
        Patch(facecolor='#00ff00', label='Start Node'),
        Patch(facecolor='#ff0000', label='Goal Node'),
        Patch(facecolor='#0088ff', label='Path Taken')
    ]
    plt.legend(handles=legend_elements, loc='upper right', bbox_to_anchor=(1.35, 1))
    plt.axis('off')
    plt.show()

# --- Execution ---
print(f"--- UGV Dynamic Environment Pathfinding ---")
true_battlefield = create_true_environment(GRID_SIZE, OBSTACLE_DENSITY)

start_node = (0, 0)
goal_node = (GRID_SIZE - 1, GRID_SIZE - 1)

# Ensure start and goal are open in the true world
true_battlefield[start_node[0]][start_node[1]] = 0
true_battlefield[goal_node[0]][goal_node[1]] = 0

print(f"Deploying UGV with a sensor range of {SENSOR_RANGE} units...")

start_time = time.perf_counter()
path_taken, final_known_world, success, recalculations = dynamic_navigation(true_battlefield, start_node, goal_node)
end_time = time.perf_counter()

# Output Measures of Effectiveness
print("\n" + "="*45)
print(" MEASURES OF EFFECTIVENESS (DYNAMIC MoE)")
print("="*45)
print(f"Total Execution Time: {((end_time - start_time) * 1000):.2f} ms")
print(f"Total Replans Issued: {recalculations} recalculations")

if success:
    print(f"Status:               Goal Reached Successfully")
    print(f"Actual Distance:      {len(path_taken) - 1} km (steps taken)")
else:
    print(f"Status:               MISSION FAILED (Trapped)")
print("="*45 + "\n")

visualize_dynamic_run(true_battlefield, final_known_world, start_node, goal_node, path_taken)